import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { FC, PropsWithChildren } from 'react'
import MainContainer from '@/components/UI/MainContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <MainContainer>{children}</MainContainer>
      </body>
    </html>
  )
}
export default RootLayout
